<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Carbon\Carbon;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Modules\Réservation\Entities\Chambre;
use Modules\Réservation\Entities\Reservation;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run()
    {
        DB::table('chambre_categories')->delete();
        DB::table('chambre_categories')->insert(
            [
                [
                    'id' => 1,
                    'nom' => 'standard',
                    'prix' => 40000,
                    'wifi' => 1,
                    'petit_dej' => 0,
                    'nbr_chb' => 1,
                    'nbr_lit' => 1,
                    'description' => "Bienvenue à notre élégante chambre d'hôtel, un havre de confort et de tranquillité. Cette chambre spacieuse offre une vue panoramique sur la ville depuis son balcon privé. Décorée avec goût, elle est dotée d'un lit king-size luxueux et d'un coin salon propice à la détente. La salle de bains en marbre est équipée d'une douche à effet pluie et d'articles de toilette haut de gamme. Profitez des équipements modernes tels qu'une télévision à écran plat, un minibar bien approvisionné et un accès Wi-Fi gratuit. Notre chambre incarne le mariage parfait entre confort contemporain et esthétique raffinée, créant ainsi un espace accueillant pour votre séjour mémorable.",
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 2,
                    'nom' => 'privilege',
                    'prix' => 55000,
                    'wifi' => 1,
                    'petit_dej' => 1,
                    'nbr_chb' => 1,
                    'nbr_lit' => 1,
                    'description' => "Bienvenue à notre élégante chambre d'hôtel, un havre de confort et de tranquillité. Cette chambre spacieuse offre une vue panoramique sur la ville depuis son balcon privé. Décorée avec goût, elle est dotée d'un lit king-size luxueux et d'un coin salon propice à la détente. La salle de bains en marbre est équipée d'une douche à effet pluie et d'articles de toilette haut de gamme. Profitez des équipements modernes tels qu'une télévision à écran plat, un minibar bien approvisionné et un accès Wi-Fi gratuit. Notre chambre incarne le mariage parfait entre confort contemporain et esthétique raffinée, créant ainsi un espace accueillant pour votre séjour mémorable.",
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 3,
                    'nom' => 'suite junior',
                    'prix' => 80000,
                    'wifi' => 1,
                    'petit_dej' => 1,
                    'nbr_chb' => 2,
                    'nbr_lit' => 3,
                    'description' => "Bienvenue à notre élégante chambre d'hôtel, un havre de confort et de tranquillité. Cette chambre spacieuse offre une vue panoramique sur la ville depuis son balcon privé. Décorée avec goût, elle est dotée d'un lit king-size luxueux et d'un coin salon propice à la détente. La salle de bains en marbre est équipée d'une douche à effet pluie et d'articles de toilette haut de gamme. Profitez des équipements modernes tels qu'une télévision à écran plat, un minibar bien approvisionné et un accès Wi-Fi gratuit. Notre chambre incarne le mariage parfait entre confort contemporain et esthétique raffinée, créant ainsi un espace accueillant pour votre séjour mémorable.",
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 4,
                    'nom' => 'suite famille',
                    'prix' => 100000,
                    'wifi' => 1,
                    'petit_dej' => 1,
                    'nbr_chb' => 3,
                    'nbr_lit' => 3,
                    'description' => "Bienvenue à notre élégante chambre d'hôtel, un havre de confort et de tranquillité. Cette chambre spacieuse offre une vue panoramique sur la ville depuis son balcon privé. Décorée avec goût, elle est dotée d'un lit king-size luxueux et d'un coin salon propice à la détente. La salle de bains en marbre est équipée d'une douche à effet pluie et d'articles de toilette haut de gamme. Profitez des équipements modernes tels qu'une télévision à écran plat, un minibar bien approvisionné et un accès Wi-Fi gratuit. Notre chambre incarne le mariage parfait entre confort contemporain et esthétique raffinée, créant ainsi un espace accueillant pour votre séjour mémorable.",
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 5,
                    'nom' => 'suite VIP',
                    'prix' => 120000,
                    'wifi' => 1,
                    'petit_dej' => 1,
                    'nbr_chb' => 3,
                    'nbr_lit' => 4,
                    'description' => "Bienvenue à notre élégante chambre d'hôtel, un havre de confort et de tranquillité. Cette chambre spacieuse offre une vue panoramique sur la ville depuis son balcon privé. Décorée avec goût, elle est dotée d'un lit king-size luxueux et d'un coin salon propice à la détente. La salle de bains en marbre est équipée d'une douche à effet pluie et d'articles de toilette haut de gamme. Profitez des équipements modernes tels qu'une télévision à écran plat, un minibar bien approvisionné et un accès Wi-Fi gratuit. Notre chambre incarne le mariage parfait entre confort contemporain et esthétique raffinée, créant ainsi un espace accueillant pour votre séjour mémorable.",
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 6,
                    'nom' => 'suite presidentielle',
                    'prix' => 180000,
                    'wifi' => 1,
                    'petit_dej' => 1,
                    'nbr_chb' => 4,
                    'nbr_lit' => 6,
                    'description' => "Bienvenue à notre élégante chambre d'hôtel, un havre de confort et de tranquillité. Cette chambre spacieuse offre une vue panoramique sur la ville depuis son balcon privé. Décorée avec goût, elle est dotée d'un lit king-size luxueux et d'un coin salon propice à la détente. La salle de bains en marbre est équipée d'une douche à effet pluie et d'articles de toilette haut de gamme. Profitez des équipements modernes tels qu'une télévision à écran plat, un minibar bien approvisionné et un accès Wi-Fi gratuit. Notre chambre incarne le mariage parfait entre confort contemporain et esthétique raffinée, créant ainsi un espace accueillant pour votre séjour mémorable.",
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 7,
                    'nom' => 'salle',
                    'prix' => 115000,
                    'wifi' => 1,
                    'petit_dej' => 1,
                    'nbr_chb' => 0,
                    'nbr_lit' => 0,
                    'description' => "Bienvenue à notre élégante chambre d'hôtel, un havre de confort et de tranquillité. Cette Salle spacieuse offre une vue panoramique sur la ville depuis son balcon privé. Décorée avec goût, elle est dotée d'un lit king-size luxueux et d'un coin salon propice à la détente. La salle de bains en marbre est équipée d'une douche à effet pluie et d'articles de toilette haut de gamme. Profitez des équipements modernes tels qu'une télévision à écran plat, un minibar bien approvisionné et un accès Wi-Fi gratuit. Notre chambre incarne le mariage parfait entre confort contemporain et esthétique raffinée, créant ainsi un espace accueillant pour votre séjour mémorable.",
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]
        );
        DB::table('chambres')->delete();
        DB::table('chambres')->insert(
            [
                [
                    'id' => 100,
                    'status' => 'libre',
                    'categorie_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 101,
                    'status' => 'libre',
                    'categorie_id' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ], [
                    'id' => 102,
                    'status' => 'libre',
                    'categorie_id' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ], [
                    'id' => 103,
                    'status' => 'libre',
                    'categorie_id' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 104,
                    'status' => 'libre',
                    'categorie_id' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 105,
                    'status' => 'libre',
                    'categorie_id' => 6,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 106,
                    'status' => 'libre',
                    'categorie_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 107,
                    'status' => 'libre',
                    'categorie_id' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 108,
                    'status' => 'libre',
                    'categorie_id' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 109,
                    'status' => 'libre',
                    'categorie_id' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 110,
                    'status' => 'libre',
                    'categorie_id' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 111,
                    'status' => 'libre',
                    'categorie_id' => 6,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 112,
                    'status' => 'libre',
                    'categorie_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 113,
                    'status' => 'libre',
                    'categorie_id' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 114,
                    'status' => 'libre',
                    'categorie_id' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 115,
                    'status' => 'libre',
                    'categorie_id' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 116,
                    'status' => 'libre',
                    'categorie_id' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 117,
                    'status' => 'libre',
                    'categorie_id' => 6,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

            ]
        );
        DB::table('users')->delete();
        DB::table('users')->insert(
            [
                [
                    'id' => 1,
                    'nom' => 'Stacy Flatley Sr.',
                    'tel' => '+22870281889',
                    'email' => 'barman@gmail.com',
                    'type_piece' => 'carte consulaire',
                    'numero_piece' => 'UA6122312',
                    'sexe' => 'M',
                    'adresse' => '6336 Kilback Freeway Apt. 851\nLake Ginaton, WV 51906',
                    'isadmin' => 'barman',
                    'password' => '$2y$10$PG.d92YYlhGNjIZ5Lvj9VOs8Gu5ZsDUvgRSspdDOqZZalqMtNFcba', // Hashed password
                    'remember_token' => 'IBqZSvywbm',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 2,
                    'nom' => 'Miles Schoen MD',
                    'tel' => '+22893281489',
                    'email' => 'reception@gmail.com',
                    'type_piece' => 'cni',
                    'numero_piece' => 'PO6062088',
                    'sexe' => 'F',
                    'adresse' => '410 Bauch Rue\nRonnyfort, OH 64207-4732',
                    'isadmin' => 'recept',
                    'password' => '$2y$10$5ak.FK1.YTEE4yqgiOxyGuvfR80i1qLkKyuAp0YHK2D.98y69HjRu', // Hashed password
                    'remember_token' => 'ZjjXTe1Uv1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 3,
                    'nom' => 'Jhon Schoen MD',
                    'tel' => '+22897891483',
                    'email' => 'restaurant@gmail.com',
                    'type_piece' => 'cni',
                    'numero_piece' => 'OM604088',
                    'sexe' => 'M',
                    'adresse' => '410 Bauch Rue\nRonnyfort, OH 64207-4732',
                    'isadmin' => 'server',
                    'password' => '$2y$10$5ak.FK1.YTEE4yqgiOxyGuvfR80i1qLkKyuAp0YHK2D.98y69HjRu', // Hashed password
                    'remember_token' => 'ZjjXTe1Uv1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 4,
                    'nom' => 'Mahamat cherif',
                    'tel' => '+22870056985',
                    'email' => 'mcherif@gmail.com',
                    'type_piece' => 'passeport',
                    'numero_piece' => 'KL904488',
                    'sexe' => 'M',
                    'adresse' => '410 Bauch Rue\nRonnyfort, OH 64207-4732',
                    'isadmin' => 'client',
                    'password' => '$2y$10$5ak.FK1.YTEE4yqgiOxyGuvfR80i1qLkKyuAp0YHK2D.98y69HjRu', // Hashed password
                    'remember_token' => 'ZjjXTe1Uv1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 5,
                    'nom' => 'Jhon Falabe',
                    'tel' => '+22870000001',
                    'email' => 'jhfalabe@gmail.com',
                    'type_piece' => 'carte consulaire',
                    'numero_piece' => 'UA6122313',
                    'adresse' => 'Adresse du client 1',
                    'sexe' => 'M',
                    'isadmin' => 'client',
                    'password' => '$2y$10$PG.d92YYlhGNjIZ5Lvj9VOs8Gu5ZsDUvgRSspdDOqZZalqMtNFcba',
                    'remember_token' => 'TokenClient1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 6,
                    'nom' => 'Andeee',
                    'tel' => 'Elwill',
                    'email' => 'aelwill0@usa.gov',
                    'type_piece' => 'carte consulaire',
                    'numero_piece' => 'QE6647843',
                    'adresse' => 'Apt 963',
                    'sexe' => 'F',
                    'isadmin' => 'client',
                    'password' => '$2y$10$PG.d92YYlhGNjIZ5Lvj9VOs8Gu5ZsDUvgRSspdDOqZZalqMtNFcba',
                    'remember_token' => 'TokenClient1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 7,
                    'nom' => 'Evyn',
                    'tel' => 'Nussen',
                    'email' => 'enussen1@over-blog.com',
                    'type_piece' => 'cni',
                    'numero_piece' => 'XW2252025',
                    'adresse' => 'PO Box 96615',
                    'sexe' => 'F',
                    'isadmin' => 'client',
                    'password' => '$2y$10$PG.d92YYlhGNjIZ5Lvj9VOs8Gu5ZsDUvgRSspdDOqZZalqMtNFcba',
                    'remember_token' => 'TokenClient2',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 8,
                    'nom' => 'Alvinia',
                    'tel' => 'Mariyushkin',
                    'email' => 'amariyushkin7@virginia.edu',
                    'type_piece' => 'carte consulaire',
                    'numero_piece' => 'FX8678779',
                    'adresse' => 'Room 1485',
                    'sexe' => 'M',
                    'isadmin' => 'client',
                    'password' => '$2y$10$PG.d92YYlhGNjIZ5Lvj9VOs8Gu5ZsDUvgRSspdDOqZZalqMtNFcba',
                    'remember_token' => 'TokenClient8',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 9,
                    'nom' => 'Alicia',
                    'tel' => 'Baiss',
                    'email' => 'abaiss8@mlb.com',
                    'type_piece' => 'passeport',
                    'numero_piece' => 'NC6456428',
                    'adresse' => '8th Floor',
                    'sexe' => 'M',
                    'isadmin' => 'client',
                    'password' => '$2y$10$PG.d92YYlhGNjIZ5Lvj9VOs8Gu5ZsDUvgRSspdDOqZZalqMtNFcba',
                    'remember_token' => 'TokenClient9',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 10,
                    'nom' => 'Abagael',
                    'tel' => 'Lindblad',
                    'email' => 'alindblad9@gizmodo.com',
                    'type_piece' => 'passeport',
                    'numero_piece' => 'YU0142031',
                    'adresse' => 'Suite 33',
                    'sexe' => 'M',
                    'isadmin' => 'client',
                    'password' => '$2y$10$PG.d92YYlhGNjIZ5Lvj9VOs8Gu5ZsDUvgRSspdDOqZZalqMtNFcba',
                    'remember_token' => 'TokenClient10',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 11,
                    'nom' => 'Shirlene',
                    'tel' => 'Englishby',
                    'email' => 'senglishby2@baidu.com',
                    'type_piece' => 'cni',
                    'numero_piece' => 'AP0048913',
                    'adresse' => 'Apt 1178',
                    'sexe' => 'F',
                    'isadmin' => 'client',
                    'password' => '$2y$10$PG.d92YYlhGNjIZ5Lvj9VOs8Gu5ZsDUvgRSspdDOqZZalqMtNFcba',
                    'remember_token' => 'TokenClient3',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 12,
                    'nom' => 'Idette',
                    'tel' => 'Instrell',
                    'email' => 'iinstrell3@google.ru',
                    'type_piece' => 'passeport',
                    'numero_piece' => 'ZD0669474',
                    'adresse' => 'Apt 1096',
                    'sexe' => 'M',
                    'isadmin' => 'client',
                    'password' => '$2y$10$PG.d92YYlhGNjIZ5Lvj9VOs8Gu5ZsDUvgRSspdDOqZZalqMtNFcba',
                    'remember_token' => 'TokenClient4',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 13,
                    'nom' => 'Raleigh',
                    'tel' => 'Rosiello',
                    'email' => 'rrosiello4@ask.com',
                    'type_piece' => 'cni',
                    'numero_piece' => 'GD5624611',
                    'adresse' => 'Apt 583',
                    'sexe' => 'F',
                    'isadmin' => 'client',
                    'password' => '$2y$10$PG.d92YYlhGNjIZ5Lvj9VOs8Gu5ZsDUvgRSspdDOqZZalqMtNFcba',
                    'remember_token' => 'TokenClient5',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 14,
                    'nom' => 'Silvanus',
                    'tel' => 'Warham',
                    'email' => 'swarham5@princeton.edu',
                    'type_piece' => 'cni',
                    'numero_piece' => 'JE1776383',
                    'adresse' => 'PO Box 12894',
                    'sexe' => 'F',
                    'isadmin' => 'client',
                    'password' => '$2y$10$PG.d92YYlhGNjIZ5Lvj9VOs8Gu5ZsDUvgRSspdDOqZZalqMtNFcba',
                    'remember_token' => 'TokenClient6',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 15,
                    'nom' => 'Desmond',
                    'tel' => 'Cordaroy',
                    'email' => 'dcordaroy6@nhs.uk',
                    'type_piece' => 'passeport',
                    'numero_piece' => 'WP5838892',
                    'adresse' => 'Suite 96',
                    'sexe' => 'M',
                    'isadmin' => 'client',
                    'password' => '$2y$10$PG.d92YYlhGNjIZ5Lvj9VOs8Gu5ZsDUvgRSspdDOqZZalqMtNFcba',
                    'remember_token' => 'TokenClient7',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

            ]
        );
        $clients = User::all();
        $chambres = Chambre::all();
        $start = Carbon::now()->format('Y-m-d');
        $end = Carbon::now()->addDays(10)->format('Y-m-d');
        foreach (range(1, 10) as $index) {
            $randomDate = Carbon::createFromFormat('Y-m-d', $start)
                ->addDays(random_int(0, Carbon::createFromFormat('Y-m-d', $end)->diffInDays($start)))
                ->format('Y-m-d');

            $dateArrive = $randomDate;
            $dateDepart = Carbon::createFromFormat('Y-m-d', $randomDate)
                ->addDays(random_int(1, 14))
                ->format('Y-m-d');
            $randomChambre = $chambres->random();
            $randomChambreCategorie = $randomChambre->chambreCategorie;
            $nbrJour = Carbon::parse($dateArrive)->diffInDays(Carbon::parse($dateDepart));
            $prix = $randomChambreCategorie->prix * $nbrJour;

            // dd($nbrJour, $randomChambreCategorie,  $prix);
            Reservation::create([
                'numero' => 'RSV' . random_int(19111111, 9999999999),
                'nbr_jour' => $nbrJour,
                'nbr_client' => random_int(1, 2),
                'prix' => $prix,
                'status' => 'attente',
                'date_arrive' => $dateArrive,
                'date_depart' => $dateDepart,
                'client_id' => $clients->random()->id,
                'chambre_id' => $randomChambre->id,
            ]);
        }
        DB::table('produits')->delete();
        DB::table('produits')->insert([
            [
                'id' => 1,
                'nom' => 'Pizza italien',
                'prix' => '3500',
                'image' => 'pizza_italien64eb88f9adbaa.jpg',
                'type' => 'nourriture',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'nom' => 'Humberger',
                'prix' => '2500',
                'image' => 'hamburger64eb89196bb56.jpg',
                'type' => 'nourriture',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'nom' => 'Humberger double',
                'prix' => '3500',
                'image' => 'Hamburger_double64eb8940098ef.jpg',
                'type' => 'nourriture',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'nom' => 'Jus d`\'orange et autres',
                'prix' => '1500',
                'image' => 'jus_orange.jpg',
                'type' => 'boisson',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'nom' => 'Boisson de tout type',
                'prix' => '1000',
                'image' => 'boisson.jpg',
                'type' => 'boisson',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'nom' => 'Café',
                'prix' => '500',
                'image' => 'cafe.jpg',
                'type' => 'boisson',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'nom' => 'Alcool de tout type',
                'prix' => '500',
                'image' => 'alcool.jpg',
                'type' => 'boisson',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        $reservations = Reservation::all();
        DB::table('services')->delete();
        DB::table('services')->insert(
            [
                [
                    'id' => 1,
                    'type_service' => 'ptdej',
                    'type_payement' => 'cash',
                    'prix' => '290500',
                    'reservation_id' => $reservations->random()->numero,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 2,
                    'type_service' => 'dej',
                    'type_payement' => 'reservation',
                    'prix' => '122500',
                    'reservation_id' => $reservations->random()->numero,
                    'created_at' => now()->subDays(1),
                    'updated_at' => now()->subDays(1),
                ],
                [
                    'id' => 3,
                    'type_service' => 'diner',
                    'type_payement' => 'reservation',
                    'prix' => '320500',
                    'reservation_id' => $reservations->random()->numero,
                    'created_at' => now()->subDays(2),
                    'updated_at' => now()->subDays(2),
                ],
                [
                    'id' => 4,
                    'type_service' => 'ptdej',
                    'type_payement' => 'cash',
                    'prix' => '441500',
                    'reservation_id' => $reservations->random()->numero,
                    'created_at' => now()->subDays(3),
                    'updated_at' => now()->subDays(3),
                ],
                [
                    'id' => 5,
                    'type_service' => 'dej',
                    'type_payement' => 'reservation',
                    'prix' => '333400',
                    'reservation_id' => $reservations->random()->numero,
                    'created_at' => now()->subDays(4),
                    'updated_at' => now()->subDays(4),
                ],
                [
                    'id' => 6,
                    'type_service' => 'diner',
                    'type_payement' => 'reservation',
                    'prix' => '198000',
                    'reservation_id' => $reservations->random()->numero,
                    'created_at' => now()->subDays(5),
                    'updated_at' => now()->subDays(5),
                ],
                [
                    'id' => 7,
                    'type_service' => 'ptdej',
                    'type_payement' => 'cash',
                    'prix' => '250500',
                    'reservation_id' => $reservations->random()->numero,
                    'created_at' => now()->subDays(6),
                    'updated_at' => now()->subDays(6),
                ],
                [
                    'id' => 9,
                    'type_service' => 'diner',
                    'type_payement' => 'reservation',
                    'prix' => '308500',
                    'reservation_id' => $reservations->random()->numero,
                    'created_at' => now()->subDays(7),
                    'updated_at' => now()->subDays(7),
                ],
                [
                    'id' => 10,
                    'type_service' => 'ptdej',
                    'type_payement' => 'cash',
                    'prix' => '480500',
                    'reservation_id' => $reservations->random()->numero,
                    'created_at' => now()->subDays(8),
                    'updated_at' => now()->subDays(8),
                ],
                [
                    'id' => 12,
                    'type_service' => 'diner',
                    'type_payement' => 'reservation',
                    'prix' => '500000',
                    'reservation_id' => $reservations->random()->numero,
                    'created_at' => now()->subDays(9),
                    'updated_at' => now()->subDays(9),
                ],
                [
                    'id' => 13,
                    'type_service' => 'ptdej',
                    'type_payement' => 'cash',
                    'prix' => '403500',
                    'reservation_id' => $reservations->random()->numero,
                    'created_at' => now()->subDays(10),
                    'updated_at' => now()->subDays(10),
                ],
                [
                    'id' => 11,
                    'type_service' => 'dej',
                    'type_payement' => 'reservation',
                    'prix' => '345000',
                    'reservation_id' => $reservations->random()->numero,
                    'created_at' => now()->subDays(11),
                    'updated_at' => now()->subDays(11),
                ],
                [
                    'id' => 8,
                    'type_service' => 'dej',
                    'type_payement' => 'reservation',
                    'prix' => '315000',
                    'reservation_id' => $reservations->random()->numero,
                    'created_at' => now()->subDays(12),
                    'updated_at' => now()->subDays(12),
                ],
            ]

        );
    }
}
